export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    DECREASE_PRODUCT_COUNT: 'DECREASE_PRODUCT_COUNT',
    INCREASE_PRODUCT_COUNT: 'INCREASE_PRODUCT_COUNT'
}